MOCK_RAW_API_S3_FILE = [
  {
    "track": {
      "album": {
        "album_type": "single",
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/21mKp7DqtSNHhCAU2ugvUw"
            },
            "href": "https://api.spotify.com/v1/artists/21mKp7DqtSNHhCAU2ugvUw",
            "id": "21mKp7DqtSNHhCAU2ugvUw",
            "name": "ODESZA",
            "type": "artist",
            "uri": "spotify:artist:21mKp7DqtSNHhCAU2ugvUw"
          },
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/6N1Kaz3CvRa9VLll5ahk9T"
            },
            "href": "https://api.spotify.com/v1/artists/6N1Kaz3CvRa9VLll5ahk9T",
            "id": "6N1Kaz3CvRa9VLll5ahk9T",
            "name": "Theodore Shapiro",
            "type": "artist",
            "uri": "spotify:artist:6N1Kaz3CvRa9VLll5ahk9T"
          }
        ],
        "available_markets": [
          "AR",
          "AU",
          "AT",
          "BE",
          "BO",
          "BR",
          "BG",
          "CA",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DK",
          "DO",
          "DE",
          "EC",
          "EE",
          "SV",
          "FI",
          "FR",
          "GR",
          "GT",
          "HN",
          "HK",
          "HU",
          "IS",
          "IE",
          "IT",
          "LV",
          "LT",
          "LU",
          "MY",
          "MT",
          "MX",
          "NL",
          "NZ",
          "NI",
          "NO",
          "PA",
          "PY",
          "PE",
          "PH",
          "PL",
          "PT",
          "SG",
          "SK",
          "ES",
          "SE",
          "CH",
          "TW",
          "TR",
          "UY",
          "US",
          "GB",
          "AD",
          "LI",
          "MC",
          "ID",
          "JP",
          "TH",
          "VN",
          "RO",
          "IL",
          "ZA",
          "SA",
          "AE",
          "BH",
          "QA",
          "OM",
          "KW",
          "EG",
          "MA",
          "DZ",
          "TN",
          "LB",
          "JO",
          "PS",
          "IN",
          "BY",
          "KZ",
          "MD",
          "UA",
          "AL",
          "BA",
          "HR",
          "ME",
          "MK",
          "RS",
          "SI",
          "KR",
          "BD",
          "PK",
          "LK",
          "GH",
          "KE",
          "NG",
          "TZ",
          "UG",
          "AG",
          "AM",
          "BS",
          "BB",
          "BZ",
          "BT",
          "BW",
          "BF",
          "CV",
          "CW",
          "DM",
          "FJ",
          "GM",
          "GE",
          "GD",
          "GW",
          "GY",
          "HT",
          "JM",
          "KI",
          "LS",
          "LR",
          "MW",
          "MV",
          "ML",
          "MH",
          "FM",
          "NA",
          "NR",
          "NE",
          "PW",
          "PG",
          "PR",
          "WS",
          "SM",
          "ST",
          "SN",
          "SC",
          "SL",
          "SB",
          "KN",
          "LC",
          "VC",
          "SR",
          "TL",
          "TO",
          "TT",
          "TV",
          "VU",
          "AZ",
          "BN",
          "BI",
          "KH",
          "CM",
          "TD",
          "KM",
          "GQ",
          "SZ",
          "GA",
          "GN",
          "KG",
          "LA",
          "MO",
          "MR",
          "MN",
          "NP",
          "RW",
          "TG",
          "UZ",
          "ZW",
          "BJ",
          "MG",
          "MU",
          "MZ",
          "AO",
          "CI",
          "DJ",
          "ZM",
          "CD",
          "CG",
          "IQ",
          "LY",
          "TJ",
          "VE",
          "ET",
          "XK"
        ],
        "external_urls": {
          "spotify": "https://open.spotify.com/album/7bNj7hUkbRbZzn36MdyvUk"
        },
        "href": "https://api.spotify.com/v1/albums/7bNj7hUkbRbZzn36MdyvUk",
        "id": "7bNj7hUkbRbZzn36MdyvUk",
        "images": [
          {
            "height": 640,
            "url": "https://i.scdn.co/image/ab67616d0000b273183bc8483f5f44416c608ca9",
            "width": 640
          },
          {
            "height": 300,
            "url": "https://i.scdn.co/image/ab67616d00001e02183bc8483f5f44416c608ca9",
            "width": 300
          },
          {
            "height": 64,
            "url": "https://i.scdn.co/image/ab67616d00004851183bc8483f5f44416c608ca9",
            "width": 64
          }
        ],
        "name": "Music To Refine To: A Remix Companion to Severance",
        "release_date": "2025-04-04",
        "release_date_precision": "day",
        "total_tracks": 7,
        "type": "album",
        "uri": "spotify:album:7bNj7hUkbRbZzn36MdyvUk"
      },
      "artists": [
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/21mKp7DqtSNHhCAU2ugvUw"
          },
          "href": "https://api.spotify.com/v1/artists/21mKp7DqtSNHhCAU2ugvUw",
          "id": "21mKp7DqtSNHhCAU2ugvUw",
          "name": "ODESZA",
          "type": "artist",
          "uri": "spotify:artist:21mKp7DqtSNHhCAU2ugvUw"
        },
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/6N1Kaz3CvRa9VLll5ahk9T"
          },
          "href": "https://api.spotify.com/v1/artists/6N1Kaz3CvRa9VLll5ahk9T",
          "id": "6N1Kaz3CvRa9VLll5ahk9T",
          "name": "Theodore Shapiro",
          "type": "artist",
          "uri": "spotify:artist:6N1Kaz3CvRa9VLll5ahk9T"
        }
      ],
      "available_markets": [
        "AR",
        "AU",
        "AT",
        "BE",
        "BO",
        "BR",
        "BG",
        "CA",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DK",
        "DO",
        "DE",
        "EC",
        "EE",
        "SV",
        "FI",
        "FR",
        "GR",
        "GT",
        "HN",
        "HK",
        "HU",
        "IS",
        "IE",
        "IT",
        "LV",
        "LT",
        "LU",
        "MY",
        "MT",
        "MX",
        "NL",
        "NZ",
        "NI",
        "NO",
        "PA",
        "PY",
        "PE",
        "PH",
        "PL",
        "PT",
        "SG",
        "SK",
        "ES",
        "SE",
        "CH",
        "TW",
        "TR",
        "UY",
        "US",
        "GB",
        "AD",
        "LI",
        "MC",
        "ID",
        "JP",
        "TH",
        "VN",
        "RO",
        "IL",
        "ZA",
        "SA",
        "AE",
        "BH",
        "QA",
        "OM",
        "KW",
        "EG",
        "MA",
        "DZ",
        "TN",
        "LB",
        "JO",
        "PS",
        "IN",
        "BY",
        "KZ",
        "MD",
        "UA",
        "AL",
        "BA",
        "HR",
        "ME",
        "MK",
        "RS",
        "SI",
        "KR",
        "BD",
        "PK",
        "LK",
        "GH",
        "KE",
        "NG",
        "TZ",
        "UG",
        "AG",
        "AM",
        "BS",
        "BB",
        "BZ",
        "BT",
        "BW",
        "BF",
        "CV",
        "CW",
        "DM",
        "FJ",
        "GM",
        "GE",
        "GD",
        "GW",
        "GY",
        "HT",
        "JM",
        "KI",
        "LS",
        "LR",
        "MW",
        "MV",
        "ML",
        "MH",
        "FM",
        "NA",
        "NR",
        "NE",
        "PW",
        "PG",
        "PR",
        "WS",
        "SM",
        "ST",
        "SN",
        "SC",
        "SL",
        "SB",
        "KN",
        "LC",
        "VC",
        "SR",
        "TL",
        "TO",
        "TT",
        "TV",
        "VU",
        "AZ",
        "BN",
        "BI",
        "KH",
        "CM",
        "TD",
        "KM",
        "GQ",
        "SZ",
        "GA",
        "GN",
        "KG",
        "LA",
        "MO",
        "MR",
        "MN",
        "NP",
        "RW",
        "TG",
        "UZ",
        "ZW",
        "BJ",
        "MG",
        "MU",
        "MZ",
        "AO",
        "CI",
        "DJ",
        "ZM",
        "CD",
        "CG",
        "IQ",
        "LY",
        "TJ",
        "VE",
        "ET",
        "XK"
      ],
      "disc_number": 1,
      "duration_ms": 131000,
      "explicit": "false",
      "external_ids": {
        "isrc": "GBCFB2500163"
      },
      "external_urls": {
        "spotify": "https://open.spotify.com/track/0gu8PxfeEncsxXKhO0g9sX"
      },
      "href": "https://api.spotify.com/v1/tracks/0gu8PxfeEncsxXKhO0g9sX",
      "id": "0gu8PxfeEncsxXKhO0g9sX",
      "is_local": "false",
      "name": "Entering Lumon - ODESZA Severance Remix",
      "popularity": 51,
      "preview_url": "null",
      "track_number": 1,
      "type": "track",
      "uri": "spotify:track:0gu8PxfeEncsxXKhO0g9sX"
    },
    "played_at": "2025-04-30T00:29:50.917Z",
    "context": {
      "external_urls": {
        "spotify": "https://open.spotify.com/album/7bNj7hUkbRbZzn36MdyvUk"
      },
      "href": "https://api.spotify.com/v1/albums/7bNj7hUkbRbZzn36MdyvUk",
      "type": "album",
      "uri": "spotify:album:7bNj7hUkbRbZzn36MdyvUk"
    }
  }
]