name: Spotify Listening History App CI/CD Pipeline

on:
  push:
  pull_request:
    branches:
      - main

jobs:

  get_test_coverage:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # - name: Set up AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: 'us-east-2'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev

      - name: Make the test script executable
        run: chmod +x pipeline_scripts/run_tests.sh

      - name: Run unit and component tests
        run: ./pipeline_scripts/run_tests.sh

  integration_tests:

    runs-on: ubuntu-latest
    needs: get_test_coverage
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies for testing
        run: |
          python -m pip install --upgrade pip
          pip install behave
          pip install -r src/lambdas/requirements.txt

      - name: Make the test script executable
        run: chmod +x pipeline_scripts/run_integration_tests.sh
  
      - name: Run integration_tests
        run: ./pipeline_scripts/run_integration_tests.sh

      - name: Upload Lambda zip as artifact
        uses: actions/upload-artifact@v4
        with:
          name: lambda-zip
          path: src/lambdas/lambda_function.zip
